### ISSUE TITLE
Problem: Redundant information needs to be passed when instantiating a BitcoinWallet

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-js-sdk#10]
**Problem:** I think we are passing redundant information to `BitcoinWallet.newInstance`. The hdKey actually encodes the network within the first four bytes: https://bitcoin.stackexchange.com/a/63996

**Goal:** 
1. Make the arguments to the APIs in `comit-js-sdk` orthogonal (creating a better developer experience)
2. Make `comit-js-sdk` portable across all networks without having to manually account for it as a developer.

**Recommendation:** Remove the `network` parameter and create it from the first four bytes of the key that we pass in. Very likely, `bcoin` has a function somewhere for doing that.

**Comment by bonomat** [comment]
The ticket is true and right about the possibility of deriving the network from the key. I see this as a relatively complicated optimization and would skip it until some developer is asking for it.
