### ISSUE TITLE
Provide means to check for Ethereum transaction status

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-js-sdk#107]
## Problem

When sending transactions, the internal `EthereumWallet` does not check for the transaction status. Meaning that if the rpc call is successful but the transaction fails, it goes unnoticed.

This is an issue that has been the cause of time wasting in e2e tests. The deployed failed but was marked as successful, making redeem/refund failed.
Investigation is then misdirected to the redeem/refund section of the deploy one.

## Goal

Report if the Ethereum transaction fails or give the lib consumer the opportunity to check themselves.

## Recommendation

```
const fundingTransaction =  await swap.fund();
> console.log(await fundingTransaction.getStatus())
"transaction failed" / "transaction confirmed" /  "transaction unconfirmed"
```

Which means a new `SwapTransaction` class could be introduced.

This change should be tested within the SDK.

Note: This is a recommendation. The objective is to provide an interface to get the status of a transaction without asking the app dev to do a lot of manual process, ie, returning the txid is not good enough.
Note: To test we need to introduce testcontainers js to test against an Ethereum node. Inspire yourself from bobtimus project.
Note: Don't worry about providing api for number of confirmations for now.
Note: This is only for Ethereum
Note: a transaction can become unconfirmed so always check the blockchain.

**Comment by bonomat** [comment]
@yosriady : as an ethereum expert :) what would be the expected behavior of the sdk in such a case?

**Comment by yosriady** [comment]
Yes, I think the SDK should provide utilities for developers to confirm transactions using an approach similar to the approach described here: https://medium.com/renproject/gatewayjs-caas-and-gaas-7e03817d8034

In other words, the COMIT SDK would provide methods to allow developers to find out the current state of swap transactions. Behind the scenes the SDK would do this by subscribing to a Bitcoin / Ethereum node for the specific transactions:

```
const mySwap =  await sdk.getSwap(<identifier>);
> console.log(mySwap.status)
"transaction failed" / "transaction succeeded" /  "transaction pending"
```

What do you think?

**Comment by D4nte** [comment]
> Note: To test we need to introduce testcontainers js to test against an Ethereum node. Inspire yourself from bobtimus project.

I believe this incorrect. We trust underlying libraries (`ethers.js`) to return the right information for a given transaction.
By testing fully e2e, we just end up testing a bit of our code and a lot of the full Ethereum + ethers.js stack.

Testing our code by mocking ethers.js should be enough to give us confidence in our code. This is what I will aim to do.

**Comment by bonomat** [comment]
> Testing our code by mocking ethers.js should be enough to give us confidence in our code. This is what I will aim to do.

I think this makes sense. 
Fully fledged e2e tests are meant for something different. I think can deal with the e2e tests separately and mock ethers.js.
