### ISSUE TITLE
Check `Transaction` status for Bitcoin

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-js-sdk#113]
## Problem

While in Bitcoin a transaction that would failed is directly rejected by bitcoind RPC call, there is value in extending #107 to Bitcoin transactions.

## Goal
Report if the Bitcoin transaction status in the blockchain.

## Recommendation

Build on top of #107.

Note: Need to extend cnd REST API mocking for testing.
Note: `Failed` for Bitcoin is a transaction considered invalid. Today the wallet would just throw an exception (to be verified) so instead, it should have a status failed.

**Comment by bonomat** [comment]
Afaik our transactions are sent to the bitcoin network through bcoin and not bitcoind. Nevertheless, the feature described should be possible.
