### ISSUE TITLE
Configure `axios` to handle problem responses

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-js-sdk#122]
# Problem

The Axios client in the SDK does not handle  the media-type `application/problem+json` as returned by `cnd` if there is a problem.
We have some some behaviour where we would like to assert on message and status of a problem response (e.g. in the `bitcoin_high_fee` e2e test).

# Goal

Properly handle the media-type `application/problem+json` in Axios so we can assert on the problem.

# Proposed Solution

Note: @thomaseizinger recommended to check for plugins that do this, but I could not find any thus the recommendation is to add this to the axios config ourselves:

Check `transformResponse` here: https://github.com/axios/axios#request-config

Transform the `problem+json` response returned by `cnd` to return a proper `Problem` class that we can assert on it in some way.

Pseudo-code:
```
await expect(responsePromise).to.be.rejected
    .and.be.instanceOf("Problem")
    .and.have.property("name", value);
```

**Comment by thomaseizinger** [comment]
Another idea would be to make a custom Error subclass and throw an instance of that in the response transformer.
I don't know how axios handles exceptions thrown there but I'd assume they just bubble up, which is what we want :)
