### ISSUE TITLE
More generic Ethereum Wallet Interface

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-js-sdk#154]
## Problem

The current API is very specialised and stops COMIT App developers to bring their own Ethereum Wallet interface.

## Goal

Provide an API that is familiar to Decentralised App devs.

## Recommendation

Add a **new** constructor that accepts a web3 provider as an argument (no breaking change).

See https://github.com/comit-network/app/issues/7#issuecomment-595041740

```js
// Before
const wallet = new EthereumWallet(
    process.env.ETHEREUM_NODE_URL, // url
    process.env.ETHEREUM_KEY // private key
);
```

```js
// After
const web3 = new Web3(...) // (or Ethers.js)
const wallet = new EthereumWallet(
  web3Provider: web3.currentProvider,
  privateKey
);
```

**Comment by yosriady** [comment]
After some more research, I think what we need is to follow the `Provider` standard similar to https://github.com/liquality/chainabstractionlayer

**Comment by bonomat** [comment]
I agree, I'll move this ticket to `To Refine`.

**Comment by yosriady** [comment]
I will work on a spike for this.

**Comment by bonomat** [comment]
I'll close this then and let @yosriady create new issues once the spike in https://github.com/comit-network/app/issues/9 was done.
