### ISSUE TITLE
Have a different README for GitHub Repo and online documentation

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-js-sdk#155]
## Problem

We currently use the README.md as entry point for the online documentation: https://comit.network/docs/comit-sdk/index

This brings several issue:
- The README is too long for the online doc
- The class/file links point to the GitHub Repos, not the generated documentation

## Goal

- Keep the user where he is (in GitHub or on the document website)
- Avoid stale links when possible (might not be in GitHub but should be possible on the doc website)

## Recommendation

- Write a doc comment in `index.ts` that will be the entrypoint for the sdk doc on https://comit.network/, also change the doc generation config to ensure it's used,
- Make the README lighter and point to the doc instead,
- Update/remove stale links in the GitHub README.

**Comment by yosriady** [comment]
> Write a doc comment in index.ts 

What do you mean by this? Do you mean using docstrings in the code?

Another way is we can create a Markdown file other than `README.md`, which will be used in the generated site. We can change the [build process](https://github.com/comit-network/comit.network/blob/master/build.sh) to modify which files are used.

**Comment by D4nte** [comment]
> > Write a doc comment in index.ts
> 
> What do you mean by this? Do you mean using docstrings in the code?
> 
> Another way is we can create a Markdown file other than `README.md`, which will be used in the generated site. We can change the [build process](https://github.com/comit-network/comit.network/blob/master/build.sh) [](/comit-network/comit.network/blob/HEAD@{2020-03-09T04:08:42Z}/build.sh) to modify which files are used.

Yes we meant docstrings in the doc but your alternative sound better.
