### ISSUE TITLE
Provide more info on classes used in example

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-js-sdk#156]
## Problem

It is not clear for a COMIT Dev app what they should understand/use in the SDK and what is internal/unnecessary for them.
Their are comments present in the example but they don't go enough in details regarding the objects that are being manipulated and what they can provide to the dev (`ComitClient`, `Swap`, `SwapDetails`, `Wallet`).

## Goal

The example is a simple "hello world" happy path use of the SDK. A developer needs to leverage more of the SDK to handle other cases, errors and corner cases. The developer needs pointer on what the SDK can do.

The goal is to add comments and highlighted the classes. Mention what they represent and direct the dev to the SDK doc.

**Comment by yosriady** [comment]
This will definitely be useful for developers seeking to build apps with the SDK.

**Comment by yosriady** [comment]
@D4nte 

I think it's also worth explaining about the `Swap` object and the status feature. I did not see any mention of it in the `demo/` and did not realize such a feature exists.

https://github.com/comit-network/comit-js-sdk/blob/9ab87203d0c204ea24c32312b1d485e4f4cea975/src/cnd/cnd.ts#L161

**Comment by D4nte** [comment]
> @D4nte
> 
> I think it's also worth explaining about the `Swap` object and the status feature. I did not see any mention of it in the `demo/` and did not realize such a feature exists.
> 
> https://github.com/comit-network/comit-js-sdk/blob/9ab87203d0c204ea24c32312b1d485e4f4cea975/src/cnd/cnd.ts#L161

Yes I have added the description to include the `Swap` clas.

**Comment by D4nte** [comment]
Issue moved to [comit-network/create-comit-app #519](https://github.com/comit-network/create-comit-app/issues/519) via [**ZenHub**](https://www.zenhub.com/)
