### ISSUE TITLE
Purpose of timeouts in example code

### ISSUE THREAD

**Issue by yosriady** [comit-network/comit-js-sdk#173]
When fetching balances from the comit client:

```
const t = await getTaker();

// Wait a second to let the Ethereum wallet catch up??
// QUESTION: For some reason the following line is needed for bitcoin balance to be displayed correctly
await new Promise(r => setTimeout(r, 1000));

const bitcoinBalance = await t.bitcoinWallet.getBalance();
const erc20Balance = await t.ethereumWallet.getErc20Balance(
    process.env.ERC20_CONTRACT_ADDRESS
);
```

If the timeout line is removed, the bitcoin wallet balance is not returned correctly (it displays 0 instead of the default `10`). Is this expected? What's the reason why we need timeouts here?

**Comment by yosriady** [comment]
The same thing is true for wallet initialization:

```
  const bitcoinWallet = await InMemoryBitcoinWallet.newInstance(
    'regtest',
    process.env.BITCOIN_P2P_URI,
    process.env[`BITCOIN_HD_KEY_${index}`]
  );
  await new Promise(r => setTimeout(r, 1000)); // QUESTION: why is this here

  const ethereumWallet = new EthereumWallet(
    process.env.ETHEREUM_NODE_HTTP_URL,
    process.env[`ETHEREUM_KEY_${index}`]
  );
```

If the timeout line is removed, the bitcoin balance is also not returned correctly.

**Comment by yosriady** [comment]
@D4nte Is it a `bcoin` issue?

**Comment by D4nte** [comment]
@yosriady not really an issue, you need to give time to the bcoin spv node to scan the blockchain to calculate the balance.

In Bitcoin, contrary to web3, it is not part of the interface to query an arbitrary account to check balance.
The wallet needs to keep track of all the transactions related to this wallet to know how much the wallet can spend.

The `sleep` is here to give such time to bcoin.
