### ISSUE TITLE
Canonical way to retrieve swaps

### ISSUE THREAD

**Issue by yosriady** [comit-network/comit-js-sdk#175]
This issue tracks some SDK questions I have about retrieving swaps.

- What's the difference between `getNewSwaps` and `getOngoingSwaps` and `getDoneSwaps`? We may want to make it clear for developers what the corresponding statuses mean.
  - Which category do expired swaps go under?
  - What if instead of having three different functions, the SDK provides a single `getSwaps({ status: ...})` that accept filtering arguments? By default, it can return all swaps regardless of status.

- I've been using `retrieveSwapById` to get a swap, is this the proper way to do it? If not, how should one get a swap?

- Why does `swap.fetchDetails()` return `SwapDetails` instead of `SwapProperties` directly? The `SwapDetails` interface seems to only contain a single `properties` attribute. In we can simplify this, perhaps `swap.toJSON()` would be a better name since it returns a serialized version of the `Swap`.

## Follow-ups
- The idea is to have a `Swap` object to manipulate and have meaningful functions available
- To re-instantiate the `Swap` object if it's not kept in the lifetime of the object, then the swap url should be used => to be extended.

@D4nte to chat with @yosriady to have an issue ready to change the SDK.

**Comment by yosriady** [comment]
@D4nte Do we have a way to retrieve a swap by URL?

**Comment by D4nte** [comment]
@yosriady actually use, the default constructor of `Swap` allows you to create it with its URL:
```
  constructor(
    private readonly cnd: Cnd,
    readonly self: string, // this is the url
    wallets: AllWallets
  ) {
    this.wallets = new Wallets(wallets);
  }
```

**Comment by yosriady** [comment]
@D4nte Where do I get its URL?

**Comment by D4nte** [comment]
> @D4nte Where do I get its URL?

`swap.self`. Can you please point to your code that handle a swap please? I am think I need more context to help.

**Comment by yosriady** [comment]
@D4nte https://github.com/comit-network/app/blob/feature/state-machines/app/containers/SwapDetailsPage.tsx#L29-L31

**Comment by D4nte** [comment]
> @D4nte [comit-network/app:state-machines/app/containers/SwapDetailsPage.tsx@`feature`#L29-L31](https://github.com/comit-network/app/blob/feature/state-machines/app/containers/SwapDetailsPage.tsx#L29-L31) [](/comit-network/app/blob/HEAD@{2020-04-09T02:13:37Z}/state-machines/app/containers/SwapDetailsPage.tsx#L29-L31)

Ok I am not skilled enough with React to understand the code. Instead of transferring an `id` around, use the self url. Where do you get the id from?

**Comment by thomaseizinger** [comment]
> What's the difference between getNewSwaps and getOngoingSwaps and getDoneSwaps? We may want to make it clear for developers what the corresponding statuses mean.

This distinction is due to our (legacy) communication protocol that required Bob to accept or decline swaps. We are working on an improvement of this that simplifies that. To answer your question, adding a single `getSwaps` function is certainly doable :)

> I've been using retrieveSwapById to get a swap, is this the proper way to do it? If not, how should one get a swap?

That function is a workaround for the above (legacy) communication protocol to make it work with the _negotiation_ protocol that is built on top of this and shouldn't really be used outside :s 

The URL of a swap is its canonical identifier. It is available through the `self` property on the swap object: https://github.com/comit-network/comit-js-sdk/blob/cef77e4f1a54a9291184cd384040a6d3af7fbd58/src/swap.ts#L30

You can reconstruct a swap object at any time through this constructor by passing in an instance of `Cnd` (the underlying HTTP client), the link to the swap and the wallets.

> Why does swap.fetchDetails() return SwapDetails instead of SwapProperties directly? The SwapDetails interface seems to only contain a single properties attribute. In we can simplify this, perhaps swap.toJSON() would be a better name since it returns a serialized version of the Swap.

No real reason apart from just not giving it enough thought really :D

**Comment by thomaseizinger** [comment]
Looking at your code I would suggest to not re-create the objects all the time :)
The swap object is designed to be stateful. I would store an instance of the `Swap` on the instance of the component and use `useEffect` to continuously call `fetchDetails` on it.

In other words: I would tie the lifetime of a `Swap` object to the lifetime of your component, with the URL being passed in through the props.

The only not so pretty part is that the full (relative) URL will need to be part of your routing logic, something like:

`http://localhost:8080/swapdetails?url=/swaps/rfc003/3f41bff9-6ad9-4b67-9040-0dab9ae08bfc`

But since the app is going to be an electron app, the URL is not visible anyway right?

**Comment by yosriady** [comment]
> > @D4nte [comit-network/app:state-machines/app/containers/SwapDetailsPage.tsx@`feature`#L29-L31](https://github.com/comit-network/app/blob/feature/state-machines/app/containers/SwapDetailsPage.tsx#L29-L31)
> 
> Ok I am not skilled enough with React to understand the code. Instead of transferring an `id` around, use the self url. Where do you get the id from?

`getOngoingSwaps()`

**Comment by yosriady** [comment]
> Looking at your code I would suggest to not re-create the objects all the time :)
> The swap object is designed to be stateful. I would store an instance of the `Swap` on the instance of the component and use `useEffect` to continuously call `fetchDetails` on it.
> 
> In other words: I would tie the lifetime of a `Swap` object to the lifetime of your component, with the URL being passed in through the props.
> 
> The only not so pretty part is that the full (relative) URL will need to be part of your routing logic, something like:
> 
> `http://localhost:8080/swapdetails?url=/swaps/rfc003/3f41bff9-6ad9-4b67-9040-0dab9ae08bfc`
> 
> But since the app is going to be an electron app, the URL is not visible anyway right?

I see, I'll refactor accordingly.

The routing is fine, and it's not visible to the user.

**Comment by yosriady** [comment]
@thomaseizinger 

> https://github.com/comit-network/comit-js-sdk/blob/cef77e4f1a54a9291184cd384040a6d3af7fbd58/src/swap.ts#L30
> 
> You can reconstruct a swap object at any time through this constructor by passing in an instance of `Cnd` (the underlying HTTP client), the link to the swap and the wallets.

Is this the canonical function that does the above: https://github.com/comit-network/comit-js-sdk/blob/d54f3ae793d18e98189c817e568242b0eb7b89e3/src/comit_client.ts#L141 ?

**Comment by thomaseizinger** [comment]
@yosriady 

The function you linked is private and only accessible by the ComitClient. But `Swap` has a public constructor that you can use:

https://github.com/comit-network/comit-js-sdk/blob/cef77e4f1a54a9291184cd384040a6d3af7fbd58/src/swap.ts#L28-L31

The `Cnd` instance is also easily constructed:

https://github.com/comit-network/comit-js-sdk/blob/cef77e4f1a54a9291184cd384040a6d3af7fbd58/src/cnd/cnd.ts#L338

Same goes for the wallets.

**Comment by yosriady** [comment]
@thomaseizinger 

I understood what we can do to use Swaps in a stateful manner. However, I'm not sure if this developer experience is easy to follow.

As you mentioned, developers would need to retrieve a Cnd instance, Bitcoin, and Ethereum wallet instances, to retrieve a swap. It feels like the app developer might be reimplementing functionality that should be in the SDK. Would it not be possible to expose an SDK helper function to retrieve a swap by its identifier (either the URL or ID)? 

In addition, is the Cnd instance meant for public consumption? The SDK does provide an `Actor` wrapper: https://github.com/comit-network/comit-js-sdk/blob/master/src/actor.ts but it's not exposing `cnd`. Based on this, I expect that app developers aren't expected to interact with the cnd instance directly. Is this interface still relevant?

**Comment by yosriady** [comment]
Closing as all open questions are answered. I'm moving forward with implementing the functions I need on the app.
