### ISSUE TITLE
Meaningful response for ledger actions

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-js-sdk#19]
Note: As part of https://github.com/comit-network/comit-js-sdk/pull/18 we introduce the `ComitClient` and `Swap` into the SDK, this allows us to execute swaps action by action instead of automatically executing the actions.

## Problem
The response we return after executing a ledger action is just the response the blockchain client returns. This is not very meaningful when printing log messages for the user.

## Goal

The SDK provides information to print meaningful log messages (on level `data`) in applications like hello swap. Given the log the user should be able to check on chain what has happened.

## Proposal

Return the transaction hash for each case statement in `doLedgerAction` of `Swap`.

**Comment by thomaseizinger** [comment]
Done in #18.
