### ISSUE TITLE
Move more code to sdk

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-js-sdk#20]
@D4nte commented on [Fri Sep 27 2019](https://github.com/comit-network/hello-swap/issues/33)

## Problem

The original `hello-swap` (no integrated into create-comit-app as `btc-eth`) contains a fair bit of code that would also be useful in other projects. In particular, most of the code around executing actions.

## Goal

Reduce the amount of code in hello-swap up to a point where you might as well write it from scratch as you need it.

## Recommendation

The current API provided by `comit-sdk` is fairly low-level. We basically have 3 main things:

- a Bitcoin wallet
- an Ethereum wallet
- a CND client

In order to do drive cnd's API, one needs to fetch the list of available swaps, iterate through the actions and execute them pass them back to the cnd instance together with a so-called `FieldValueResolver`: a callback function that fills in all the necessary data. This `FieldValueResolver` is very likely to be the same in all environments.

We should provide an API to users (on top of what we currently have), that looks more like this:

- Instantiate a `ComitClient` (suggestions for a better name welcome) from
	- a BitcoinWallet
	- an EthereumWallet
	- a cnd instance
- Fetching swaps give you a list of `Swap` instances
- A swap instance has methods on it for:
	- accept
	- decline
	- fund
	- refund
	- redeem

Those methods don't take any arguments and do whatever is necessary to execute the given functionality.

**Comment by thomaseizinger** [comment]
Done in #18.
