### ISSUE TITLE
Target network for Ethereum actions is ignored

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-js-sdk#21]
## Problem

Currently, we ignore the `network` parameter of the action that is returned from cnd: 

https://github.com/comit-network/hello-swap/blob/e5ea4f98215722c3d2eb1b59e35ad4ae30c4bc20/src/helloSwap.ts#L300-L332

Both `action.payload` would have a `network` parameter that is currently not used.

## Goal

Make sure we don't execute actions on a network that they are not meant for, i.e. cnd tells us to execute an action on ropsten but our wallet is connected to a mainnet node.

## Recommendation

With https://github.com/comit-network/comit-js-sdk/issues/4, we will be able to pass a chainId to methods defined on the wallets in the SDK.

Because of https://github.com/comit-network/RFCs/issues/73, we will still have to do a mapping between the network returned by `cnd` and a chainId.
The current mapping is (source https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md#list-of-chain-ids):

mainnet => 1,
ropsten => 3,
regtest => 17 (is one is used by parity's `dev` config

**Comment by yosriady** [comment]
How are the current network of the Ethereum wallet currently determined? Would it be possible to instantiate the wallet like so:

```
const ethereumProvider = new HDWalletProvider(process.env.MNEMONIC, RINKEBY_ENDPOINT);
const wallet = new EthereumWallet(provider, { network: 'rinkeby' });
```

**Comment by D4nte** [comment]
> How are the current network of the Ethereum wallet currently determined? Would it be possible to instantiate the wallet like so:
> 
> ```
> const ethereumProvider = new HDWalletProvider(process.env.MNEMONIC, RINKEBY_ENDPOINT);
> const wallet = new EthereumWallet(provider, { network: 'rinkeby' });
> ```

As per this issue, currently you do not need to pass the network. You only pass the ethereum Provider. One Ethereum Provider only support one network so the network is the one of the provider.

Once this issue is done we hope that you can pass a network to the `EthereumWallet` that will check that the passed provider is connected to the specified network.

**Comment by thomaseizinger** [comment]
Removed "to-refine" as the description of the ticket is fairly precise IMO.
