### ISSUE TITLE
Public API is not sufficiently tested against breaking changes

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-js-sdk#220]
## Problem

PR https://github.com/comit-network/comit-js-sdk/pull/183 accidentially introduced a breaking change by removing the InMemoryBitcoinWallet from the public export of the library.
In an effort of releasing fewer breaking changes, 0.15.3 was released which caused the new version to be picked automatically when people started using it through create-comit-app.

## Goal

To not accidentially introduce breaking changes.

## Recommendation

Use some kind of automation to draw attention to the developer if they introduce breaking changes.

Ideas:
- automated tests
- checking TS type declarations into Git and compare them against a new build
- survey other tools in the ecosystem, we can't be the only one solving that problem

**Comment by D4nte** [comment]
Taking over as per comment in #238
