### ISSUE TITLE
Separate API for execution specific parameters that are confusing in `MakerNegotiator`

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-js-sdk#228]
Note: Not sure how much time we want to invest into the negotiation module of the SDK, given that we want to tackle the negotiation when researching decentralised order-books. Thus, I did not invest too much time into writing this up.

## Problem

This issue was created when working on the Tutorial #4 - it is hard to understand why the `ExecutionParams` and `TryParams` are necessary to create a `MakerNegotiator`. 

The execution parameters in the form currently depicted, are (partly) not negotiation relevant and could be separated from the negotiation.

## Goal

Clearer separation of negotiation from execution, making it easier for the app-dev to understand what both phases are about and what is needed for a certain phase (e.g. the peer-id is needed for execution, not for negotiation, but at the moment it seems it is used for negotiation.)

Only price-relevant parameters should exist in the negotiator. 

## Proposed Solution

Create another endpoint on the maker's HTTP interface, that would allow a user to explicitly get certain information relevant for execution. 

From the top of my head: peer-id, address-hint; and the `TryParams`
Expiries are discussable, as they might be negotiation relevant.

The remaining price relevant "ExecutionParams" in the `MakerNegotiatior can be renamed (?).

**Comment by D4nte** [comment]
I believe the problem is more deeply rooted to the fact that we have to poll cnd for updates and to trigger actions. I'd be more interested in offering a push API than trying to hack this interface.

**Comment by da-kami** [comment]
@D4nte I think the polling nature of cnd is only partly related to this problem.
 
Even if cnd pushes actions to the application the peer-id, address-hint and expiries still have to be exchanged between the parties before communication can start (concretely: Bob has to give Alice information - at the moment this information is part of the `MakerNegotiator`). I think this execution specific information should be separate from the `MakerNegotiator`. 

However, given that we might tackle (part of) this problem when researching the decentralised orderbook I will close this ticket for now.

**Comment by da-kami** [comment]
After reading through @thomaseizinger technical-debt post on Basecamp I would actually re-open this and mark it as `technical-debt`. I think it is valid to keep tracking this problem, even though we might tackle it later...?
Feel free to close this again @D4nte if you don't agree.

**Comment by thomaseizinger** [comment]
Agreed to mark as technical-debt, although I would like to be more problem focused then and maybe contain some information about how we got to this point.

In this case, I guess things like: we have a poll-based interface, hence the try params and we have not discovery, hence the required PeerID.
