### ISSUE TITLE
Developer has to know the RFC003 steps

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-js-sdk#30]
## Problem

The developer has to know the steps (and order) that Alice/Bob have to take to execute a swap.
If a party sends erc20, the developer has to know that a deploy step is needed.

## Goal

The sdk should provide enough functionality so that the developer does not need to know about RFC3 execution.

## Note

It looks like the sdk was recently optimised to run and demonstrate how a swap occurs instead of focusing in providing a developer friendly interface.

## Recommendation

To be discussed, the `Swap.fund()` etc functions are not needed. They can remain exposed for advanced developers and the sake of the examples/e2e tests.

Provide a new `Swap.execute()` function that runs through all steps.

**Comment by bonomat** [comment]
Moving my thought from the slack conversation here:
I agree, we should improve the UX massively to make life easier for the developer.
But I also think that it is crucial that the developer is aware of the required steps of an Atomic Swap. The goal should be to find a trade off, i.e. the sdk should _guide_ him through the steps needs to do a swap.

**Comment by da-kami** [comment]
This cycles around the question how powerful the SDK should be and the example strategy.

I think the SDK could offer both. We do not have the jack of all trades now, and we build a lot on assumptions. We could then ask people what they like better. We can also ask them without having the functionality, but then it might be tough to get a meaningful answer. 

I see three stages, that could be three examples at the moment: 
1. just call `execute()` and the SDK does everything (periodically check which action is available and then execute it)
2. have `fund()` and `redeem()` and call them "in order" without checking which action is actually available (current `erc20-btc` example)
3. periodically check which action is available in the example and then calling `fund()` or `redeem()`. This would be an updated version of the `btc-eth` example (the old `helloSwap.ts`).

**Comment by D4nte** [comment]
Please note the origin of this issue is that I was doing a `deploy()` on an Ether-Bitcoin swap and hence it was failing.

The fact that a dev knows he should do `deploy()` for erc20 but not for other currencies is what I want to challenge more than anything.

**Comment by da-kami** [comment]
After discussion last week we decided that developers build on top of COMIT should always be confronted with the swap steps in the examples. `execute()` is an abstraction layer too much.

We stick to the current form as in the `erc20-btc` example.
