### ISSUE TITLE
Cannot generate random Bitcoin wallet

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-js-sdk#31]
## Problem

With #26, we introduced the ability to generate a random Ethereum wallet. The same cannot be done for Bitcoin, for which providing a HD key is mandatory. Helpful for e2e tests.

## Goal

Be able to quickly generate a Bitcoin wallet without the overhead of having to generate a HD key.

## Solution

Make the HD key parameter optional when constructing a new Bitcoin Wallet. Instead randomly generate it inside or use a `bcoin` API that handles it for you if it exists.

**Comment by bonomat** [comment]
Closing this for now: with the latest version a developer could provide his own Bitcoin Wallet and hence, could overcome this if needed.
