### ISSUE TITLE
Extend `comit-js-sdk` documentation

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-js-sdk#54]
## Problem

There is basically no documentation around the `comit-js-sdk` besides the README at the moment. A proper SDK should have some API documentation so that developers can educate themselves.

## Goals

Short-run:
* Developers that take a look at the project (README) should be impressed and motived to use it.

Long-run:
* Developers that build an application on top of COMIT should be able to get (detailed) information about the SDK that goes beyond the examples in `create-comit-app`.

## Proposal

Focus on the short-running goal for now:
* Add comments to the SDK code that adhere to the [JSDoc](https://devdocs.io/jsdoc/) spec.
* Add a tiny example to the SDK README that shows very basic usage (can be pseudocode).
* Keep the link to create-comit-app
* Add section that explains basic functions/functionality

More detailed documentation can be added at a later point if needed.

**Comment by da-kami** [comment]
Nice to have for the Hackathon, but not a must for me.

**Comment by yosriady** [comment]
A high-level documentation of the negotation protocol would be very useful. :pray:

**Comment by yosriady** [comment]
A high-level documentation of the negotation protocol would be very useful. :pray:
Third-party developers should not have to dig through the code to find out how COMIT works.

In particular:
- An explanation of the [Order](https://github.com/comit-network/create-comit-app/blob/master/new_project/examples/btc_eth/src/index.ts#L100-L122) message schema.
- An explanation of the steps of the COMIT protocol.

A great reference is the [0x documentation](https://0x.org/docs/core-concepts#the-0x-order-message-format).

**Comment by bonomat** [comment]
Closing this in favor of the epic: https://github.com/coblox/admin/issues/159 which tracks the documentation.
