### ISSUE TITLE
Provide conversion from bignumber.js to ethers.utils

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-js-sdk#82]
## Problem

As per https://github.com/comit-network/comit-rs/pull/1775#issuecomment-570123886

To be refined...

**Comment by thomaseizinger** [comment]
There is also a native bigint type in Javascript: https://tc39.es/proposal-bigint/

**Comment by D4nte** [comment]
Closing for now as the issue I was facing is because I was doing `toString()` on a `Promise`....

**Comment by D4nte** [comment]
> There is also a native bigint type in Javascript: [tc39.es/proposal-bigint](https://tc39.es/proposal-bigint/)

Only seems to be a draft but definitely worth keeping an eye on it,.

**Comment by thomaseizinger** [comment]
> > There is also a native bigint type in Javascript: [tc39.es/proposal-bigint](https://tc39.es/proposal-bigint/)
> 
> Only seems to be a draft but definitely worth keeping an eye on it.

Draft4 means it is definitely going in :)

Typescript seems to support it already: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint

**Comment by D4nte** [comment]
I see that node 11 and chrome support bigint. Not sure what is the best strategy here.

**Comment by thomaseizinger** [comment]
Should look for a polyfill to support it on older engines.
