### ISSUE TITLE
Refactor EthereumWallet so that developers can provide their own wallet implementation

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-js-sdk#85]
# Problem

Given our own preferences and experience with Bcoin we would not use the provided Bitcoin wallet in production ourselves. 
For `BitcoinWallet` we provide already an interface to do so but not for EthereumWallet

# Goal

Allow developers to provide their own wallet implementations, i.e. refactor `Actor` so that it accepts interfaces of `BitcoinWallet` and `EthereumWallet`.

Note: done for `BitcoinWalelt`: 
https://github.com/comit-network/comit-js-sdk/blob/0305e0e1c1e56eb801cec40f436538e96fa66d59/src/bitcoinWallet.ts#L4

The provided interface needs to offer functionality so that we can keep using the abstraction in `Swap` (`fund` etc).

# Sub step

Once this ticket is done, update the readme and state that we had some unpleasant experience with Bcoin and that one can _easily_ provide their own wallet. 
Also mention the _limitation_ our bitcoin wallet (based on bcoin) has: https://github.com/comit-network/comit-js-sdk/issues/9

**Comment by D4nte** [comment]
Replaced by #154.
