### ISSUE TITLE
Taker's order criteria

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-js-sdk#89]
## Problem

To get an order, the taker needs to go through several hoops:
1. Get orders from maker by doing `TakerNegotiator.getOrderByTradingPair("ETH-BTC")`
1. Do manual sanity checks on the order: https://github.com/comit-network/create-comit-app/blob/e2718a60bf7319e2504bb355c0406b00da0ae055/create/new_project/examples/separate_apps/src/taker.ts#L49
1. Manually check that the rate is acceptable: https://github.com/comit-network/create-comit-app/blob/e2718a60bf7319e2504bb355c0406b00da0ae055/create/new_project/examples/separate_apps/src/taker.ts#L67
1. Take the order using `TakerNegotiator.takeOrder(order)`: https://github.com/comit-network/create-comit-app/blob/e2718a60bf7319e2504bb355c0406b00da0ae055/create/new_project/examples/separate_apps/src/taker.ts#L73

The downsides are:
- The taker needs to specify the criteria in several steps (first pair, then check itself)
- Validation of the order is manual, a dev would expect to be able to do `Order.validate()` or even only return valid orders from the `TakerNegotiator.getOrderByTradingPair` call by filtering
- The filtering is quite manual and forces the dev to work through the properties of the order

## Goal

Provide a straightforward, function based, API to the developer. Alleviate the work.

## Recommendation

Re-think the API describe above to simplify it.
A better flow would be:

```
const criteria = {
	buy: "BTC",
	sell: "ETH",
	btcAmount: 0.5,
	allowOffersWithLesserAmount: false,
	maximumRate: 10
}

// Probably revise the `TakerNegotiator` terminology
const order = await takerNegotiator.getOffer(criteria);

if (!order.isValid()) { // This is an optional call and could/should be done already by `getOffer`
	// Ban this maker
}

if (!order.matches()) {  // This is an optional call and could/should be done already by `getOffer`
	// Tell the user why we cannot find an appropriate order
	console.log("Order found but does not match criteria", order.matchFailReason());
	// -> "Order found but does not match criteria { reason: 'maximumRate exceeded', expected: 10, actual: 15 }"
	// -> "Order found but does not match criteria { reason: 'lesser amount provided and not allowed', expected: 0.5, actual: 0.1 }"
}

const swap = await order.take();
```

**Comment by D4nte** [comment]
@yosriady what do you think about the proposed flow?

**Comment by yosriady** [comment]
@D4nte 

Looks better! The core idea is to automatically give users a pre-filtered list of acceptable orders to take from.

```
const order = await takerNegotiator.getOffer(criteria);
```

What's an 'offer'? Would this function return one or a list of valid offers?

**Comment by bonomat** [comment]
> ```
> const criteria = {
>	buy: "BTC",
>	sell: "ETH",
>	btcAmount: 0.5,
>	allowOffersWithLesserAmount: false,
>	maximumRate: 10
>}
>```

If I understand this correctly than the taker has to know a _suitable_ rate beforehand? 

If so, then I'm against it as it does not reflect a real world use. A taker does not know the rate before asking for it.

**Comment by D4nte** [comment]
> > ```
> > const criteria = {
> >   buy: "BTC",
> >   sell: "ETH",
> >   btcAmount: 0.5,
> >   allowOffersWithLesserAmount: false,
> >   maximumRate: 10
> > }
> > // Probably revise the `TakerNegotiator` terminology
> > const order = await takerNegotiator.getOffer(criteria);
> > ...
> > ```
> 
> Are these fields optional?
> 
> //Ignore what was written here before :) //

Some field are likely to be optional while other are mandatory.
