### ISSUE TITLE
Receive address is re-used

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-js-sdk#9]
## Problem:
We always start at receive index zero when we initialize the wallet. That is the default value inside the bcoin library.

## Goal:
Don't reuse the same address here for receiving funds, even if the application restarts and the number of already derived receive addresses is lost.

## Recommendation:
I am not sure what the best approach is. We would probably have to lookahead 100 receive addressses and check, which one the last one was that we received money on and initialize the receive index with that. For this we would always have to scan the whole blockchain at startup. This is fine for regtest but not practical for testnet/mainnet.

I think the solution will have to be manifold:
- calling back to the application to persist some state, receive & change address index for example
- last block hash that we scanned
- usage of an SPV node?

**Comment by thomaseizinger** [comment]
This has changed now a bit but we still re-use the same addresses between restarts of the wallet. Should probably use an SPV node.

**Comment by bonomat** [comment]
Closing this as we don't want that/don't think anyone will use the provided bitcoin wallet bcoin. 
For testnet/demo purposes we can live with this minor issue.

**Comment by thomaseizinger** [comment]
> don't think anyone will use the provided bitcoin wallet bcoin

Which wallet should they use instead?
I don't think we should hide these problems by closing issues. If the wallet has limitations and we want to accept that, then this should be documented.

**Comment by bonomat** [comment]
> Which wallet should they use instead?

Whatever wallet they want to :) This is already possible through the interface of `BitcoinWallet`. 

We can obviously add a disclaimer in the readme. 
I've created a ticket to add an abstraction for `EthereumWallet` as well so that we also don't force developers to use our provided wallet: https://github.com/comit-network/comit-js-sdk/issues/85
