### ISSUE TITLE
Unnecessary steps to create `TakerNegotiator`

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-js-sdk#90]
_This could be done hand in hand with #89 and/or #88_

## Problem

The `TakerNegotiator` must be instantiated in 2 steps:

```
const makerClient = new MakerClient("http://localhost:2318/");
const takerNegotiator = new TakerNegotiator(taker.comitClient, makerClient);
```

## Goal

Provide a simple and easy API.

## Recommendation

One step instantiation:
```
const takerNegotiator = new TakerNegotiator(taker.comitClient, "http://localhost:2318/");
```
Also, re-think about the usage of a hard-coded url here.
Documenting it may be enough:

```
// The MAKER_URL is to be provided by the other party.
// The other party can use `MakerNegotiator.getUrl()` to provide such url
const MAKER_URL = "http://localhost:2318/";
const takerNegotiator = new TakerNegotiator(taker.comitClient, MAKER_URL);
```

**Comment by yosriady** [comment]
Yes, the current instantiation doesn't mean anything to third-party developers and may be confusing.

**Comment by D4nte** [comment]
Done with #407
