### ISSUE TITLE
Test `ComitClient` logic

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-js-sdk#96]
## Problem

Currently, `ComitClient` is hardly tested. That means, if there is a bug in this logic, we could end up doing  something which could harm the user (e.g. accidentally swapping `target_ledger` and `source_ledger`)

## Goal

Be robust and maintain it by reviewing how to make the sdk robust to runtime failures.

## Recommendation

1. Identify _external_ calls especially in comit_client.ts (e.g, calls to cnd),
1. Test the logic by mocking the cnd response,
1. Leverage the test coverage to know what logic is not yet tested.

Note: There are already a number of tests in here using jest mocking features if you need inspirations.

**Comment by bonomat** [comment]
Moved back to-groom as I repurposed this ticket to make it more explicit of what should be tested.
