### ISSUE TITLE
Test external calls (cnd.ts)

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-js-sdk#97]
## Problem

If cnd goes down or a library throw an exception, it's finished.

## Goal

Be robust and maintain it by reviewing how to make the sdk robust to runtime failures (cnd call times out, functions throwing errors).

## Recommendation

1. Identify _external_ calls especially in cnd.ts (e.g, calls to external libraries, network, io, etc).
1. Protect those calls (`try` ?)
1. Test these protections: Jest has good way to do some mockings.

**Comment by D4nte** [comment]
Have a look at #111 as it can be one way to do this issue.
