### ISSUE TITLE
Test coverage tool for SDK

### ISSUE THREAD

**Issue by da-kami** [comit-network/comit-js-sdk#98]
## Problem

We do not know how much of the SDK is tested

## Goal

Introduce and **document** a test coverage tool to measure progress of code quality.
This is to be used locally by the developer to assist with new code.

Then update #97 with what should be tested using the coverage.

## Recommendation

`jest --coverage`

**Comment by D4nte** [comment]
Better do #1927 first as this propose to use `jest` and `jest` will only be introduced by #1927.

**Comment by bonomat** [comment]
@da-kami / @D4nte / @thomaseizinger: before I invest more time into this I have two questions:
1) is this ticket done with _just_ introducing test coverage generation? Or do we want a bot which posts the coverage report as a comment on github? 
2) what was meant with the second part?
> and document a test coverage tool to measure progress of code quality.

**Comment by D4nte** [comment]
> @da-kami / @D4nte / @thomaseizinger: before I invest a lot of time into this I have two questions:
> 
>     1. is this ticket done with _just_ introducing test coverage generation? Or do we want a bot which posts the coverage report as a comment on github?
> 
>     2. what was meant with the second part?
> 
> 
> > and document a test coverage tool to measure progress of code quality.

The second part is about looking at code which is not covered and saying "ok we should test that" in #97.
